[config]
schemaVersion = "0.0.1"

[package]
namespace = "JngoCreates"
name = "InnerEigong"
versionNumber = "0.5.0"
description = "Mods the true final boss of Nine Sols to be more difficult. "
websiteUrl = "https://github.com/jngo102/InnerEigong"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
